image: node:9.1-alpine

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test

before_script:
  - apk --no-cache add git openssh g++ gcc libgcc libstdc++ linux-headers make python
  - yarn install

test:
  stage: test
  script:
    - make run-coverage
  artifacts:
    paths:
      - coverage
  only:
    - master

test-lint:
  stage: test
  script:
    - make test-lint
  only:
    - master